#!/usr/bin/python3

import json
import re

import lxml.etree
import requests

html = lxml.etree.HTML(requests.get("http://myanimelist.net/anime/season").text)
for item in html.cssselect(".seasonal-anime"):
    title = item.cssselect('.link-title')[0]
    genres = item.cssselect('.genres')[0]
    desc = item.cssselect('.synopsis')[0]

    link = title.get("href")
    img = item.cssselect(".image img")[0]
    img_tag = '<img src="%s" />' % (img.get("src") or img.get("data-src"))

    print((json.dumps({
        'url': link,
        'id': link,
        'title': title.text,
        'body': '<p>%s</p> <p>%s</p> <p>%s</p> <p>%s</p>' % (lxml.etree.tostring(title).decode(), img_tag, lxml.etree.tostring(desc).decode(), lxml.etree.tostring(genres).decode()),
        'host': 'myanimelist.net'
    })))
