#!/usr/bin/python3

import scraplib
import sys
import json

def scrap_mangareader(url):
	url = scraplib.urljoin("http://www.mangareader.net", url)
	doc = yield from scraplib.fetch(url)
	for chapter in doc("#latestchapters > ul > li").pq():
		print(json.dumps({
			"title": chapter.text(),
			"body": '<a href="%s">%s</a>' % (chapter("a").url(), chapter.text()),
			"id": "mangareader:"+chapter("a").url()
		}))

if len(sys.argv) < 2 or "-h" in sys.argv or "--help" in sys.argv:
	print("Usage: %s manga-index-url" % sys.argv[0])
	sys.exit(1)

scraplib.main(scrap_mangareader(sys.argv[1]))
